apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-volume-ssurakasi
spec:
  storageClassName: rook-ceph-block-tide
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi